In [2]:
import pandas as pd
import numpy as np

data = {
    "order_id": [1001, 1002, 1003, 1004, 1005,
                 1006, 1007, 1008, 1009, 1010],

    "customer_city": [
        "Chennai", " chennai ", "BENGALURU", "Hyderabad", "mumbai",
        "CHENNAI", None, "Pune", " pune ", "HYDERABAD"
    ],

    "product_name": [
        "Python Basics", "Data Science 101", "Atomic Habits",
        "Deep Work", "Rich Dad Poor Dad", "Clean Code",
        "The Alchemist", "Think and Grow Rich", "Ikigai",
        "The Psychology of Money"
    ],

    "quantity": [2, 1, 3, 1, 2, 1, 4, 2, -1, 3],

    "unit_price": [
        "₹450", "550", "₹399", "invalid", "₹299",
        "₹650", "350", "₹250", "₹499", "₹399"
    ],

    "discount_percent": [
        10, 5, np.nan, 15, 0, 10, 5, np.nan, 10, 110
    ],

    "order_date": [
        "2026-10-01", "02/10/2026", "2026/10/03", "04-10-2026",
        "2026-10-05", "06/10/2026", "2026-10-07", "08-10-2026",
        "2026/10/09", "10/10/2026"
    ],

    "payment_method": [
        "UPI", " credit card ", "COD", "UPI", "Debit Card",
        "upi", "Net Banking", None, "COD", "CREDIT CARD"
    ],

    "delivery_days": [3, 5, 2, 7, 4, 6, 3, 999, 5, 4],

    "order_status": [
        "Delivered", "delivered", "SHIPPED", "Delivered",
        "Cancelled", "Delivered", "Pending", "shipped",
        "CANCELLED", "Delivered"
    ]
}

df = pd.DataFrame(data)

df.head(10)

,order_id,customer_city,product_name,quantity,unit_price,discount_percent,order_date,payment_method,delivery_days,order_status
0,1001,Chennai,Python Basics,2,₹450,10.0,2026-10-01,UPI,3,Delivered
1,1002,chennai,Data Science 101,1,550,5.0,02/10/2026,credit card,5,delivered
2,1003,BENGALURU,Atomic Habits,3,₹399,NaN,2026/10/03,COD,2,SHIPPED
3,1004,Hyderabad,Deep Work,1,invalid,15.0,04-10-2026,UPI,7,Delivered
4,1005,mumbai,Rich Dad Poor Dad,2,₹299,0.0,2026-10-05,Debit Card,4,Cancelled
5,1006,CHENNAI,Clean Code,1,₹650,10.0,06/10/2026,upi,6,Delivered
6,1007,NaN,The Alchemist,4,350,5.0,2026-10-07,Net Banking,3,Pending
7,1008,Pune,Think and Grow Rich,2,₹250,NaN,08-10-2026,NaN,999,shipped
8,1009,pune,Ikigai,-1,₹499,10.0,2026/10/09,COD,5,CANCELLED
9,1010,HYDERABAD,The Psychology of Money,3,₹399,110.0,10/10/2026,CREDIT CARD,4,Delivered

In [3]:
print("Number of rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

print("\nSummary statistics:")
display(df.describe(include="all"))

Number of rows and columns: (10, 10)

Column names:
['order_id', 'customer_city', 'product_name', 'quantity', 'unit_price', 'discount_percent', 'order_date', 'payment_method', 'delivery_days', 'order_status']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10 non-null     int64
 1   customer_city     9 non-null      str
 2   product_name      10 non-null     str
 3   quantity          10 non-null     int64
 4   unit_price        10 non-null     str
 5   discount_percent  8 non-null      float64
 6   order_date        10 non-null     str
 7   payment_method    9 non-null      str
 8   delivery_days     10 non-null     int64
 9   order_status      10 non-null     str
dtypes: float64(1), int64(3), str(6)
memory usage: 932.0 bytes

Summary statistics:

,order_id,customer_city,product_name,quantity,unit_price,discount_percent,order_date,payment_method,delivery_days,order_status
count,10.00000,9,10,10.000000,10,8.000000,10,9,10.00000,10
unique,NaN,9,10,NaN,9,NaN,10,7,NaN,7
top,NaN,Chennai,Python Basics,NaN,₹399,NaN,2026-10-01,UPI,NaN,Delivered
freq,NaN,1,1,NaN,2,NaN,1,2,NaN,4
mean,1005.50000,NaN,NaN,1.800000,NaN,20.625000,NaN,NaN,103.80000,NaN
std,3.02765,NaN,NaN,1.398412,NaN,36.394417,NaN,NaN,314.54475,NaN
min,1001.00000,NaN,NaN,-1.000000,NaN,0.000000,NaN,NaN,2.00000,NaN
25%,1003.25000,NaN,NaN,1.000000,NaN,5.000000,NaN,NaN,3.25000,NaN
50%,1005.50000,NaN,NaN,2.000000,NaN,10.000000,NaN,NaN,4.50000,NaN
75%,1007.75000,NaN,NaN,2.750000,NaN,11.250000,NaN,NaN,5.75000,NaN
max,1010.00000,NaN,NaN,4.000000,NaN,110.000000,NaN,NaN,999.00000,NaN

In [4]:
df.isnull()

,order_id,customer_city,product_name,quantity,unit_price,discount_percent,order_date,payment_method,delivery_days,order_status
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,True,False,True,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False

In [5]:
missing_count = df.isnull().sum()

print("Missing values in each column:")
print(missing_count)

Missing values in each column:
order_id            0
customer_city       1
product_name        0
quantity            0
unit_price          0
discount_percent    2
order_date          0
payment_method      1
delivery_days       0
order_status        0
dtype: int64

In [6]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print("Missing-value percentage:")
print(missing_percentage)

Missing-value percentage:
order_id             0.0
customer_city       10.0
product_name         0.0
quantity             0.0
unit_price           0.0
discount_percent    20.0
order_date           0.0
payment_method      10.0
delivery_days        0.0
order_status         0.0
dtype: float64

In [7]:
missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (
        df.isnull().sum() / len(df) * 100
    ).round(2)
})

missing_report = missing_report[
    missing_report["Missing_Count"] > 0
]

display(missing_report)

                  Missing_Count  Missing_Percentage
customer_city                 1                10.0
discount_percent              2                20.0
payment_method                1                10.0

In [8]:
df_original = df.copy()

In [9]:
df_work = df.copy()

df_work["customer_city"] = (
    df_work["customer_city"].fillna("Unknown")
)

df_work["payment_method"] = (
    df_work["payment_method"].fillna("Unknown")
)

df_work["discount_percent"] = (
    df_work["discount_percent"].fillna(
        df_work["discount_percent"].median()
    )
)

print("Missing values after handling:")
print(df_work.isnull().sum())

Missing values after handling:
order_id            0
customer_city       0
product_name        0
quantity            0
unit_price          0
discount_percent    0
order_date          0
payment_method      0
delivery_days       0
order_status        0
dtype: int64

In [10]:
# Check every row for duplicates
duplicate_check = df.duplicated()

print(duplicate_check)

# Count duplicate rows
print("\nTotal duplicate rows:", df.duplicated().sum())

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

Total duplicate rows: 0

In [11]:
# Find repeated order IDs
repeated_ids = df["order_id"].duplicated(keep=False)

print("Records with repeated order IDs:")
display(df[repeated_ids])

print("Number of records with repeated order IDs:", repeated_ids.sum())

Records with repeated order IDs:

Empty DataFrame
Columns: [order_id, customer_city, product_name, quantity, unit_price, discount_percent, order_date, payment_method, delivery_days, order_status]
Index: []

Number of records with repeated order IDs: 0

In [12]:
order_counts = df["order_id"].value_counts()

print("Order ID occurrences:")
print(order_counts)

print("\nOrder IDs appearing more than once:")
print(order_counts[order_counts > 1])

Order ID occurrences:
order_id
1001    1
1002    1
1003    1
1004    1
1005    1
1006    1
1007    1
1008    1
1009    1
1010    1
Name: count, dtype: int64

Order IDs appearing more than once:
Series([], Name: count, dtype: int64)

In [13]:
duplicate_records = df[
    df.duplicated(subset="order_id", keep=False)
].sort_values("order_id")

display(duplicate_records)

Empty DataFrame
Columns: [order_id, customer_city, product_name, quantity, unit_price, discount_percent, order_date, payment_method, delivery_days, order_status]
Index: []

In [14]:
# Create a separate DataFrame for analysis
df_analysis = df.copy()

# Remove the rupee symbol and extra spaces
df_analysis["unit_price"] = (
    df_analysis["unit_price"]
    .str.replace("₹", "", regex=False)
    .str.strip()
)

# Convert prices to numeric values
df_analysis["unit_price"] = pd.to_numeric(
    df_analysis["unit_price"],
    errors="coerce"
)

print(df_analysis[["product_name", "unit_price"]])

              product_name  unit_price
0            Python Basics       450.0
1         Data Science 101       550.0
2            Atomic Habits       399.0
3                Deep Work         NaN
4        Rich Dad Poor Dad       299.0
5               Clean Code       650.0
6            The Alchemist       350.0
7      Think and Grow Rich       250.0
8                   Ikigai       499.0
9  The Psychology of Money       399.0

In [15]:
# Select records suitable for revenue analysis
valid_orders = df_analysis[
    df_analysis["unit_price"].notna()
    & (df_analysis["quantity"] > 0)
    & df_analysis["discount_percent"].between(0, 100)
].copy()

# Calculate order value
valid_orders["order_value"] = (
    valid_orders["quantity"]
    * valid_orders["unit_price"]
    * (1 - valid_orders["discount_percent"] / 100)
).round(2)

display(
    valid_orders[
        ["order_id", "customer_city", "product_name",
         "quantity", "unit_price", "discount_percent", "order_value"]
    ]
)

,order_id,customer_city,product_name,quantity,unit_price,discount_percent,order_value
0,1001,Chennai,Python Basics,2,450.0,10.0,810.0
1,1002,chennai,Data Science 101,1,550.0,5.0,522.5
4,1005,mumbai,Rich Dad Poor Dad,2,299.0,0.0,598.0
5,1006,CHENNAI,Clean Code,1,650.0,10.0,585.0
6,1007,NaN,The Alchemist,4,350.0,5.0,1330.0

In [16]:
city_analysis = (
    valid_orders.groupby("customer_city")
    .agg(
        total_orders=("order_id", "count"),
        total_quantity=("quantity", "sum"),
        total_revenue=("order_value", "sum"),
        average_order_value=("order_value", "mean"),
        median_order_value=("order_value", "median")
    )
    .round(2)
    .sort_values("total_revenue", ascending=False)
)

display(city_analysis)

,total_orders,total_quantity,total_revenue,average_order_value,median_order_value
customer_city,,,,,
Chennai,1,2,810.0,810.0,810.0
mumbai,1,2,598.0,598.0,598.0
CHENNAI,1,1,585.0,585.0,585.0
chennai,1,1,522.5,522.5,522.5

In [17]:
print("Highest revenue:")
display(city_analysis.head(1))

print("Lowest revenue:")
display(city_analysis.tail(1))

Highest revenue:

,total_orders,total_quantity,total_revenue,average_order_value,median_order_value
customer_city,,,,,
Chennai,1,2,810.0,810.0,810.0

Lowest revenue:

,total_orders,total_quantity,total_revenue,average_order_value,median_order_value
customer_city,,,,,
chennai,1,1,522.5,522.5,522.5

In [18]:
highest_price = df_analysis["unit_price"].max()

print("Highest unit price: ₹", highest_price)

Highest unit price: ₹ 650.0

In [19]:
highest_index = df_analysis["unit_price"].idxmax()

highest_priced_item = df_analysis.loc[highest_index]

print("Highest-priced item details:")
print(highest_priced_item)

Highest-priced item details:
order_id                  1006
customer_city          CHENNAI
product_name        Clean Code
quantity                     1
unit_price               650.0
discount_percent          10.0
order_date          06/10/2026
payment_method             upi
delivery_days                6
order_status         Delivered
Name: 5, dtype: object

In [20]:
top_five = df_analysis.nlargest(
    5, "unit_price"
)[["product_name", "unit_price", "quantity", "customer_city"]]

print("Top 5 highest-priced books:")
display(top_five)

Top 5 highest-priced books:

       product_name  unit_price  quantity customer_city
5        Clean Code       650.0         1       CHENNAI
1  Data Science 101       550.0         1      chennai
8            Ikigai       499.0        -1         pune
0     Python Basics       450.0         2       Chennai
2     Atomic Habits       399.0         3     BENGALURU

In [21]:
print("Highest price:", df_analysis["unit_price"].max())

print("\nPrice summary:")
print(df_analysis["unit_price"].describe())

print("\nRecords with invalid or missing prices:")
display(df_analysis[df_analysis["unit_price"].isna()])

Highest price: 650.0

Price summary:
count      9.000000
mean     427.333333
std      125.389393
min      250.000000
25%      350.000000
50%      399.000000
75%      499.000000
max      650.000000
Name: unit_price, dtype: float64

Records with invalid or missing prices:

,order_id,customer_city,product_name,quantity,unit_price,discount_percent,order_date,payment_method,delivery_days,order_status
3,1004,Hyderabad,Deep Work,1,NaN,15.0,04-10-2026,UPI,7,Delivered

In [22]:
print("========== FINAL DATA QUALITY REPORT ==========")

print("\n1. Dataset shape:")
print(df.shape)

print("\n2. Missing values by column:")
print(df.isnull().sum())

print("\n3. Total missing values:")
print(df.isnull().sum().sum())

print("\n4. Duplicate rows:")
print(df.duplicated().sum())

print("\n5. Duplicate order IDs:")
print(df["order_id"].duplicated().sum())

print("\n6. Highest valid unit price:")
print("₹", df_analysis["unit_price"].max())

print("\n7. Highest-priced item:")
print(df_analysis.loc[
    df_analysis["unit_price"].idxmax(), "product_name"
])

print("\n8. Revenue by city:")
display(city_analysis)

========== FINAL DATA QUALITY REPORT ==========

1. Dataset shape:
(10, 10)

2. Missing values by column:
order_id            0
customer_city       1
product_name        0
quantity            0
unit_price          0
discount_percent    2
order_date          0
payment_method      1
delivery_days       0
order_status        0
dtype: int64

3. Total missing values:
4

4. Duplicate rows:
0

5. Duplicate order IDs:
0

6. Highest valid unit price:
₹ 650.0

7. Highest-priced item:
Clean Code

8. Revenue by city:

,total_orders,total_quantity,total_revenue,average_order_value,median_order_value
customer_city,,,,,
Chennai,1,2,810.0,810.0,810.0
mumbai,1,2,598.0,598.0,598.0
CHENNAI,1,1,585.0,585.0,585.0
chennai,1,1,522.5,522.5,522.5